//! Generates `circuits/lib/src/tx_vectors.nr`: real witness data (Merkle
//! paths, Grumpkin Schnorr signatures) for the circuit-level tests of the
//! state-transition relation in tx.nr/batch.nr. Signing can't happen inside
//! Noir tests (scalar arithmetic lives in the other field of the cycle), so
//! the harness — already vector-gated against the circuits — produces it.
//!
//! Regenerate: `cargo run -p harness -- noir-tx-vectors` (deterministic:
//! fixed keys and signing nonces, no RNG).

use crate::batch::{build_batch, tx_message, BatchWitness, DepositRequest, SignedTx};
use crate::keys::{coord_to_fr, sign_with_nonce, Keypair, Signature};
use crate::poseidon::{fr_from_u64, to_hex, Fr, Hasher, FR_ZERO};
use crate::tree::{Account, Tree, DEPTH, DOMAIN_LEAF};
use ark_grumpkin::{Fq as Coord, Fr as Scalar};
use std::fmt::Write as _;

const WD_DEST: u64 = 770_007; // arbitrary withdrawal to_field for tests

fn sibs(s: &[Fr; DEPTH]) -> String {
    let inner: Vec<String> = s.iter().map(to_hex).collect();
    format!("[{}]", inner.join(", "))
}

fn sig_lit(sig: &Signature) -> String {
    let (lo, hi) = sig.s_limbs();
    format!(
        "Signature {{ r_x: {}, r_y: {}, s_lo: {}, s_hi: {} }}",
        to_hex(&sig.r_x),
        to_hex(&sig.r_y),
        to_hex(&lo),
        to_hex(&hi)
    )
}

#[allow(clippy::too_many_arguments)]
fn tx_lit(
    from: (&Fr, &Fr, u32, u64, u64, &[Fr; DEPTH]),
    to_field: &Fr,
    to: (u32, &Fr, u64, &[Fr; DEPTH]),
    amount: u64,
    is_withdraw: bool,
    is_active: bool,
    sig: &Signature,
) -> String {
    format!(
        "TxWitness {{\n        from_pk_x: {}, from_pk_y: {}, from_index: {}, from_balance: {}, from_nonce: {},\n        from_siblings: {},\n        to_field: {}, to_index: {}, to_balance: {}, to_nonce: {},\n        to_siblings: {},\n        amount: {}, is_withdraw: {}, is_active: {},\n        sig: {},\n    }}",
        to_hex(from.0), to_hex(from.1), from.2, from.3, from.4, sibs(from.5),
        to_hex(to_field), to.0, to_hex(to.1), to.2, sibs(to.3),
        amount, is_withdraw as u8, is_active as u8, sig_lit(sig)
    )
}

fn dep_lit(pk_x: &Fr, amount: u64, index: u32, old: (&Fr, u64, u64), siblings: &[Fr; DEPTH], is_active: bool) -> String {
    format!(
        "DepositWitness {{\n        pk_x: {}, amount: {}, index: {}, old_pk_x: {}, old_balance: {}, old_nonce: {},\n        siblings: {},\n        is_active: {},\n    }}",
        to_hex(pk_x), amount, index, to_hex(old.0), old.1, old.2, sibs(siblings), is_active as u8
    )
}

fn leaf(hasher: &Hasher, pk_x: &Fr, balance: &Fr, nonce: u64) -> Fr {
    hasher.hash(&[fr_from_u64(DOMAIN_LEAF), *pk_x, *balance, fr_from_u64(nonce)])
}

/// A signed withdrawal witness against a tree whose ONLY account sits at
/// index 0 — the to-slot identity update then targets slot 0, whose sibling
/// path is unchanged by the debit (the debited leaf is the running node, not
/// a sibling). `post_debit_balance` is a raw field so overdraft wraparound
/// can be represented.
struct SoloWithdraw {
    root: Fr,
    from_siblings: [Fr; DEPTH],
    post_debit_leaf: Fr,
}

fn solo_withdraw(hasher: &Hasher, tree: &Tree, pk_x: &Fr, post_debit_balance: Coord, new_nonce: u64) -> SoloWithdraw {
    let root = tree.root(hasher);
    let (from_siblings, _) = tree.path(hasher, 0);
    let post = leaf(hasher, pk_x, &coord_to_fr(&post_debit_balance), new_nonce);
    SoloWithdraw { root, from_siblings, post_debit_leaf: post }
}

pub fn emit() -> String {
    let hasher = Hasher::new();
    let mut out = String::new();

    let alice = Keypair::from_sk(Scalar::from(101u64));
    let bob = Keypair::from_sk(Scalar::from(202u64));
    let wd_field = fr_from_u64(WD_DEST);

    writeln!(out, "// GENERATED by `cargo run -p harness -- noir-tx-vectors` - DO NOT EDIT.").unwrap();
    writeln!(out, "// Real Merkle paths + Grumpkin Schnorr signatures for tx_test.nr; the").unwrap();
    writeln!(out, "// signing side lives in the harness (vector-gated against these circuits).").unwrap();
    writeln!(out, "use crate::schnorr::Signature;").unwrap();
    writeln!(out, "use crate::tx::{{DepositWitness, TxWitness}};\n").unwrap();

    // --- Scenario A: full batch<2,2> (2 deposits, transfer + withdrawal) ---
    let mut tree = Tree::new();
    let t1_msg_nonce = Scalar::from(1001u64);
    let t2_msg_nonce = Scalar::from(1002u64);
    let t1 = {
        let msg = tx_message(&hasher, alice.pk_x(), bob.pk_x(), 250_000, 0, false);
        SignedTx {
            from_pk_x: alice.pk_x(),
            from_pk_y: alice.pk_y(),
            to_field: bob.pk_x(),
            amount: 250_000,
            nonce: 0,
            is_withdraw: false,
            sig: sign_with_nonce(&hasher, &alice, msg, t1_msg_nonce),
        }
    };
    let t2 = {
        let msg = tx_message(&hasher, bob.pk_x(), wd_field, 100_000, 0, true);
        SignedTx {
            from_pk_x: bob.pk_x(),
            from_pk_y: bob.pk_y(),
            to_field: wd_field,
            amount: 100_000,
            nonce: 0,
            is_withdraw: true,
            sig: sign_with_nonce(&hasher, &bob, msg, t2_msg_nonce),
        }
    };
    let w: BatchWitness = build_batch(
        &hasher,
        &mut tree,
        2,
        2,
        &[
            DepositRequest { pk_x: alice.pk_x(), amount: 1_000_000 },
            DepositRequest { pk_x: bob.pk_x(), amount: 500_000 },
        ],
        &[t1, t2],
    )
    .expect("scenario A must build");

    writeln!(out, "/// Scenario A: deposits alice 1_000_000 + bob 500_000, then alice->bob").unwrap();
    writeln!(out, "/// transfer 250_000 and bob withdrawal 100_000. Returns the five public").unwrap();
    writeln!(out, "/// inputs then the witness arrays.").unwrap();
    writeln!(
        out,
        "pub fn batch_a() -> ([Field; 5], [DepositWitness; 2], [TxWitness; 2]) {{\n    let pis = [{}, {}, {}, {}, {}];",
        to_hex(&w.old_root),
        to_hex(&w.new_root),
        to_hex(&w.deposit_hash),
        to_hex(&w.withdraw_hash),
        to_hex(&w.da_commitment)
    )
    .unwrap();
    let deps: Vec<String> = w
        .deposits
        .iter()
        .map(|d| dep_lit(&d.pk_x, d.amount, d.index, (&d.old_pk_x, d.old_balance, d.old_nonce), &d.siblings, d.is_active))
        .collect();
    writeln!(out, "    let deps = [{}];", deps.join(", ")).unwrap();
    let txs: Vec<String> = w
        .txs
        .iter()
        .map(|t| {
            tx_lit(
                (&t.from_pk_x, &t.from_pk_y, t.from_index, t.from_balance, t.from_nonce, &t.from_siblings),
                &t.to_field,
                (t.to_index, &t.to_balance_or_leaf, t.to_nonce, &t.to_siblings),
                t.amount,
                t.is_withdraw,
                t.is_active,
                &t.sig,
            )
        })
        .collect();
    writeln!(out, "    let txs = [{}];", txs.join(", ")).unwrap();
    writeln!(out, "    (pis, deps, txs)\n}}\n").unwrap();

    // --- Solo-tree adversarial withdrawals (account at index 0) ---
    // Helper closure: emit `pub fn NAME() -> (Field, TxWitness)` for a signed
    // withdrawal by `kp` from a solo tree with `balance`, witness fields
    // possibly diverging from what was signed.
    let mut solo_case = |name: &str,
                         doc: &str,
                         kp: &Keypair,
                         balance: u64,
                         signed_amount: u64,
                         witness_amount: u64,
                         signed_nonce: u64,
                         witness_nonce: u64,
                         k: u64| {
        let mut t = Tree::new();
        t.set(0, Account { pk_x: kp.pk_x(), balance, nonce: 0 });
        // Post-debit balance in the field (may wrap on overdraft).
        let post = Coord::from(balance) - Coord::from(witness_amount);
        let sw = solo_withdraw(&hasher, &t, &kp.pk_x(), post, witness_nonce + 1);
        let msg = tx_message(&hasher, kp.pk_x(), wd_field, signed_amount, signed_nonce, true);
        let sig = sign_with_nonce(&hasher, kp, msg, Scalar::from(k));
        writeln!(out, "/// {doc}").unwrap();
        writeln!(
            out,
            "pub fn {name}() -> (Field, TxWitness) {{\n    let w = {};\n    ({}, w)\n}}\n",
            tx_lit(
                (&kp.pk_x(), &kp.pk_y(), 0, balance, witness_nonce, &sw.from_siblings),
                &wd_field,
                (0, &sw.post_debit_leaf, 0, &sw.from_siblings),
                witness_amount,
                true,
                true,
                &sig,
            ),
            to_hex(&sw.root)
        )
        .unwrap();
    };

    solo_case(
        "overdraft",
        "Signed overdraft: amount 2_000_000 > balance 1_000_000. Sig is VALID; only the 64-bit range check on the debited balance can reject it.",
        &alice, 1_000_000, 2_000_000, 2_000_000, 0, 0, 2002,
    );
    solo_case(
        "amount_not_signed",
        "Witness amount 200_000 differs from the signed 100_000: the in-circuit message must diverge and the signature check must fail (sig binds amount).",
        &alice, 1_000_000, 100_000, 200_000, 0, 0, 3003,
    );
    solo_case(
        "zero_amount",
        "Signed zero-amount spend (free nonce burn). Sig valid; only the amount != 0 guard rejects.",
        &alice, 1_000_000, 0, 0, 0, 0, 5005,
    );
    solo_case(
        "future_nonce",
        "Signed for nonce 1 while the tree holds nonce 0: witness self-consistent (sig verifies) but the sender inclusion proof must fail - replay/skip protection via root binding.",
        &alice, 1_000_000, 100_000, 100_000, 1, 1, 6006,
    );

    // Negated padding key: same x as PAD_PK_X but even y - the blacklist must
    // reject it even though signature and parity checks pass.
    let pad_neg = Keypair::from_sk_raw(-Scalar::from(7u64));
    assert_eq!(to_hex(&pad_neg.pk_x()), crate::keys::PAD_PK_X_HEX, "negated pad shares x");
    solo_case(
        "pad_spend",
        "Spend by the (public) padding key, negated to even-y so signature AND parity checks pass: only the PAD_PK_X blacklist can reject it.",
        &pad_neg, 1_000_000, 100_000, 100_000, 0, 0, 4004,
    );

    // Odd-y sender: raw keypair whose pk has odd y (not canonicalized).
    let odd = (2u64..64)
        .map(|sk| Keypair::from_sk_raw(Scalar::from(sk)))
        .find(|kp| {
            use ark_ff::{BigInteger, PrimeField};
            kp.pk.y.into_bigint().is_odd() && to_hex(&kp.pk_x()) != crate::keys::PAD_PK_X_HEX
        })
        .expect("some small sk has odd y");
    solo_case(
        "odd_y_sender",
        "Sender pk with odd y (non-canonical). Signature is valid over it; only the is_even_y gate rejects.",
        &odd, 1_000_000, 100_000, 100_000, 0, 0, 7007,
    );

    // --- Transfer to the padding account (corrupt tree contains PAD) ---
    {
        let mut t = Tree::new();
        let pad = Keypair::from_sk_raw(Scalar::from(7u64));
        t.set(0, Account { pk_x: alice.pk_x(), balance: 1_000_000, nonce: 0 });
        t.set(1, Account { pk_x: pad.pk_x(), balance: 7, nonce: 0 });
        let root = t.root(&hasher);
        let (from_sibs, _) = t.path(&hasher, 0);
        let msg = tx_message(&hasher, alice.pk_x(), pad.pk_x(), 100_000, 0, false);
        let sig = sign_with_nonce(&hasher, &alice, msg, Scalar::from(8008u64));
        // Recipient witness against the post-debit tree.
        t.set(0, Account { pk_x: alice.pk_x(), balance: 900_000, nonce: 1 });
        let (to_sibs, _) = t.path(&hasher, 1);
        writeln!(out, "/// Transfer TO the padding account (tree corruptly contains PAD at index 1").unwrap();
        writeln!(out, "/// with balance 7). All proofs and the signature are valid; only the").unwrap();
        writeln!(out, "/// to_field != PAD_PK_X guard rejects.").unwrap();
        writeln!(
            out,
            "pub fn transfer_to_pad() -> (Field, TxWitness) {{\n    let w = {};\n    ({}, w)\n}}\n",
            tx_lit(
                (&alice.pk_x(), &alice.pk_y(), 0, 1_000_000, 0, &from_sibs),
                &pad.pk_x(),
                (1, &fr_from_u64(7), 0, &to_sibs),
                100_000,
                false,
                true,
                &sig,
            ),
            to_hex(&root)
        )
        .unwrap();
    }

    // --- Deposit negatives ---
    {
        // Ghost state under an empty slot.
        let t = Tree::new();
        let root = t.root(&hasher);
        let (sibs0, _) = t.path(&hasher, 0);
        writeln!(out, "/// Deposit init on an empty slot claiming a nonzero prior balance (ghost").unwrap();
        writeln!(out, "/// state). Must be rejected (empty-slot pinning + inclusion).").unwrap();
        writeln!(
            out,
            "pub fn ghost_deposit() -> (Field, DepositWitness) {{\n    let w = {};\n    ({}, w)\n}}\n",
            dep_lit(&alice.pk_x(), 100, 0, (&FR_ZERO, 5, 0), &sibs0, true),
            to_hex(&root)
        )
        .unwrap();

        // pk mismatch on an occupied slot.
        let mut t = Tree::new();
        t.set(0, Account { pk_x: bob.pk_x(), balance: 500_000, nonce: 0 });
        let root = t.root(&hasher);
        let (sibs0, _) = t.path(&hasher, 0);
        writeln!(out, "/// Deposit into bob's occupied slot claiming alice's pk. Inclusion of the").unwrap();
        writeln!(out, "/// true pre-state is valid; only old_pk_x == pk_x rejects.").unwrap();
        writeln!(
            out,
            "pub fn deposit_pk_mismatch() -> (Field, DepositWitness) {{\n    let w = {};\n    ({}, w)\n}}\n",
            dep_lit(&alice.pk_x(), 100, 0, (&bob.pk_x(), 500_000, 0), &sibs0, true),
            to_hex(&root)
        )
        .unwrap();

        // Balance overflow past u64.
        let mut t = Tree::new();
        t.set(0, Account { pk_x: alice.pk_x(), balance: u64::MAX - 10, nonce: 0 });
        let root = t.root(&hasher);
        let (sibs0, _) = t.path(&hasher, 0);
        writeln!(out, "/// Deposit pushing the balance past u64::MAX. Everything valid except the").unwrap();
        writeln!(out, "/// 64-bit range check on the credited balance.").unwrap();
        writeln!(
            out,
            "pub fn deposit_overflow() -> (Field, DepositWitness) {{\n    let w = {};\n    ({}, w)\n}}\n",
            dep_lit(&alice.pk_x(), 100, 0, (&alice.pk_x(), u64::MAX - 10, 0), &sibs0, true),
            to_hex(&root)
        )
        .unwrap();
    }

    // --- Inactive (padding) entries: identity property fixtures ---
    {
        let mut t = Tree::new();
        t.set(0, Account { pk_x: alice.pk_x(), balance: 1_000_000, nonce: 0 });
        let root = t.root(&hasher);
        let (sibs0, _) = t.path(&hasher, 0);
        let slot0_leaf = leaf(&hasher, &alice.pk_x(), &fr_from_u64(1_000_000), 0);
        let pad_sig = crate::keys::pad_signature(&hasher);
        writeln!(out, "/// Padding entries over a tree with alice at slot 0: inactive deposit and").unwrap();
        writeln!(out, "/// inactive tx (PAD signature). apply_* must leave root and folds unchanged.").unwrap();
        writeln!(
            out,
            "pub fn inactive_entries() -> (Field, DepositWitness, TxWitness) {{\n    let d = {};\n    let t = {};\n    ({}, d, t)\n}}\n",
            dep_lit(&FR_ZERO, 0, 0, (&alice.pk_x(), 1_000_000, 0), &sibs0, false),
            tx_lit(
                (&alice.pk_x(), &FR_ZERO, 0, 1_000_000, 0, &sibs0),
                &FR_ZERO,
                (0, &slot0_leaf, 0, &sibs0),
                0,
                false,
                false,
                &pad_sig,
            ),
            to_hex(&root)
        )
        .unwrap();
    }

    out
}
