#!/usr/bin/env bash
# Bootstrap a fresh Soribium deployment on Stellar testnet:
#   - generate + friendbot-fund the sequencer account
#   - build the rollup wasm and export the batch_n16 verification key
#   - deploy the native-asset SAC (the pinned SEP-41 token) + the rollup
#   - write .env consumed by docker-compose
#
# Idempotent-ish: reuses the sequencer identity if it exists; always deploys a
# fresh contract (VK is immutable, so a new circuit == a new instance).
set -euo pipefail
cd "$(dirname "$0")/.."

NET=testnet
IDENTITY=soribium-seq
CIRCUIT=batch_n16

echo "==> sequencer identity"
stellar keys generate "$IDENTITY" --network "$NET" --fund 2>/dev/null || stellar keys fund "$IDENTITY" --network "$NET" 2>/dev/null || true
SEQ_ADDR=$(stellar keys address "$IDENTITY")
SEQ_SECRET=$(stellar keys show "$IDENTITY")
echo "    $SEQ_ADDR"

echo "==> building rollup wasm"
stellar contract build >/dev/null
WASM=target/wasm32v1-none/release/rollup.wasm

echo "==> exporting $CIRCUIT verification key"
export PATH="$HOME/.nargo/bin:$HOME/.bb:$PATH"
( cd circuits && nargo compile --package "$CIRCUIT" >/dev/null \
  && bb write_vk --scheme ultra_honk --oracle_hash keccak \
       --bytecode_path "target/${CIRCUIT}.json" --output_path "target/${CIRCUIT}-vk" >/dev/null )
VK_BIN="circuits/target/${CIRCUIT}-vk/vk"
VK_LEN=$(wc -c < "$VK_BIN" | tr -d ' ')
[ "$VK_LEN" = "1760" ] || { echo "unexpected VK length $VK_LEN"; exit 1; }
VK=$(xxd -p "$VK_BIN" | tr -d '\n')

echo "==> deploying native SAC token"
stellar contract asset deploy --asset native --source "$IDENTITY" --network "$NET" 2>/dev/null || true
TOKEN=$(stellar contract id asset --asset native --network "$NET")
echo "    $TOKEN"

echo "==> genesis root (empty depth-8 tree)"
GENESIS=$(cargo run -q -p sequencer -- genesis-root)
GENESIS_HEX=${GENESIS#0x}

echo "==> deploying rollup contract"
ROLLUP=$(stellar contract deploy --wasm "$WASM" --source "$IDENTITY" --network "$NET" -- \
  --token "$TOKEN" --vk "$VK" --genesis_root "$GENESIS_HEX")
echo "    $ROLLUP"

echo "==> writing .env"
cat > .env <<EOF
# Generated by scripts/bootstrap_testnet.sh — gitignored, testnet-only.
RPC_URL=https://soroban-testnet.stellar.org
NETWORK_PASSPHRASE="Test SDF Network ; September 2015"
CONTRACT_ID=$ROLLUP
TOKEN_ID=$TOKEN
SEQUENCER_SECRET=$SEQ_SECRET
SEQUENCER_ADDRESS=$SEQ_ADDR
BATCH_MAX_WAIT_SECS=30
EOF

echo
echo "Bootstrap complete. Next:"
echo "  docker compose up -d --build      # sequencer + wallet"
echo "  open http://localhost:3000"
echo
echo "Apple Silicon: the sequencer image is amd64 (emulated). For fast local"
echo "dev instead run it natively:  just sequencer   (reads .env)"
