// The crypto gate: the wallet's Poseidon2 + Grumpkin + Schnorr + encodings
// must reproduce, byte-for-byte, the vectors the circuits and harness are
// pinned against. A red suite here means the wallet would produce signatures
// the circuit rejects — so this MUST pass before any UI ships (and it runs in
// the Docker build).
//
// Golden values come from fixtures/vectors.json — the single source of truth
// generated by `cargo run -p harness -- vectors-json` and drift-gated by
// scripts/check_vectors.sh (the Noir tests pin the same values as constants).
import { describe, expect, it } from 'vitest';
import vectors from '../../../fixtures/vectors.json';
import { addressToField } from './addressToField';
import { Fr, frToHex32, hexToFr, N_GRUMPKIN, randScalar } from './fields';
import { pkFromSk } from './grumpkin';
import { computeRoot, leafValue, verifyPath } from './merkle';
import { DOMAIN_DEP, DOMAIN_WD, p2 } from './poseidon2';
import { daFold, sign, txMessage, verify } from './schnorr';

const PK7_X = hexToFr(vectors.pad.pk_x);
const PK7_Y = hexToFr(vectors.pad.pk_y);
const R_X = hexToFr(vectors.pad.r_x);
const R_Y = hexToFr(vectors.pad.r_y);
const S_LO = hexToFr(vectors.pad.s_lo);
const S_HI = hexToFr(vectors.pad.s_hi);

const HASH2_1_2 = hexToFr(vectors.hash2_1_2);
const HASH4_1_2_3_4 = hexToFr(vectors.hash4_1_2_3_4);
const EMPTY_ROOT_D8 = hexToFr(vectors.empty_root_d8);
const LEAF_1234_100_0 = hexToFr(vectors.leaf_1234_100_0);
const ROOT_LEAF_AT_5 = hexToFr(vectors.root_leaf_at_5);
const DA_FOLD_0_42 = hexToFr(vectors.da_fold_0_42);

const ALICE_PK_X = hexToFr(vectors.alice_pk_x);
const BOB_PK_X = hexToFr(vectors.bob_pk_x);
const DEPOSIT_HASH = hexToFr(vectors.demo.deposit_hash);
const WITHDRAW_HASH = hexToFr(vectors.demo.withdraw_hash);
const DA_COMMITMENT = hexToFr(vectors.demo.da_commitment);
const WD_DEST = vectors.wd_dest;

const SIG7 = { r_x: R_X, r_y: R_Y, s_lo: S_LO, s_hi: S_HI };

describe('poseidon2 vs pinned circuit constants', () => {
  it('hash2(1,2)', () => expect(p2([1n, 2n])).toBe(HASH2_1_2));
  it('hash4(1,2,3,4)', () => expect(p2([1n, 2n, 3n, 4n])).toBe(HASH4_1_2_3_4));
  it('daFold(0,42)', () => expect(daFold(0n, 42n)).toBe(DA_FOLD_0_42));
});

describe('grumpkin key derivation', () => {
  it('pk(7) matches schnorr_test.nr', () => {
    const pk = pkFromSk(7n);
    expect(pk.x).toBe(PK7_X);
    expect(pk.y).toBe(PK7_Y);
  });
  it('pk(101)/pk(202) match meta.json deposits', () => {
    expect(pkFromSk(101n).x).toBe(ALICE_PK_X);
    expect(pkFromSk(202n).x).toBe(BOB_PK_X);
  });
});

describe('schnorr signature vector (sk=7, k=13, msg=42)', () => {
  it('produces the pinned signature byte-for-byte', () => {
    const sig = sign(7n, 42n, 13n);
    expect(frToHex32(sig.r_x)).toBe(frToHex32(R_X));
    expect(frToHex32(sig.r_y)).toBe(frToHex32(R_Y));
    expect(frToHex32(sig.s_lo)).toBe(frToHex32(S_LO));
    expect(frToHex32(sig.s_hi)).toBe(frToHex32(S_HI));
  });
  it('verify accepts the vector', () => {
    expect(verify(PK7_X, PK7_Y, 42n, SIG7)).toBe(true);
  });
  it('verify rejects wrong message', () => {
    expect(verify(PK7_X, PK7_Y, 43n, SIG7)).toBe(false);
  });
  it('verify rejects tampered s', () => {
    expect(verify(PK7_X, PK7_Y, 42n, { ...SIG7, s_lo: SIG7.s_lo + 1n })).toBe(false);
  });
  it('verify rejects wrong signer', () => {
    const pk8 = pkFromSk(8n);
    expect(verify(pk8.x, pk8.y, 42n, SIG7)).toBe(false);
  });
});

describe('fold chains vs meta.json', () => {
  it('deposit_hash', () => {
    const acc1 = p2([DOMAIN_DEP, 0n, ALICE_PK_X, 1000n]);
    const acc2 = p2([DOMAIN_DEP, acc1, BOB_PK_X, 500n]);
    expect(acc2).toBe(DEPOSIT_HASH);
  });
  it('withdraw_hash (exercises addressToField)', () => {
    const wd = p2([DOMAIN_WD, 0n, addressToField(WD_DEST), 100n]);
    expect(wd).toBe(WITHDRAW_HASH);
  });
  it('addressToField and txMessage match the harness directly', () => {
    expect(frToHex32(addressToField(WD_DEST))).toBe(vectors.wd_dest_field);
    expect(frToHex32(txMessage(ALICE_PK_X, BOB_PK_X, 200n, 0n, false))).toBe(
      vectors.tx_message_alice_bob_200_0,
    );
  });
  it('da_commitment (two-tx fold through txMessage)', () => {
    const msg1 = txMessage(ALICE_PK_X, BOB_PK_X, 200n, 0n, false);
    const msg2 = txMessage(BOB_PK_X, addressToField(WD_DEST), 100n, 0n, true);
    expect(daFold(daFold(0n, msg1), msg2)).toBe(DA_COMMITMENT);
  });
});

describe('encoding + roundtrips', () => {
  it('frToHex32 pads leading zeros', () => {
    expect(frToHex32(1n)).toBe('0x' + '0'.repeat(63) + '1');
    expect(hexToFr(frToHex32(S_LO))).toBe(S_LO);
  });
  it('hexToFr rejects malformed input', () => {
    expect(() => hexToFr('0x1')).toThrow();
    expect(() => hexToFr('deadbeef')).toThrow();
  });
  it('random sign/verify roundtrips', () => {
    for (let i = 0; i < 8; i++) {
      const sk = randScalar();
      const pk = pkFromSk(sk);
      const msg = randScalar() % N_GRUMPKIN;
      const sig = sign(sk, msg);
      expect(verify(pk.x, pk.y, msg, sig)).toBe(true);
      expect(verify(pk.x, pk.y, (msg + 1n) % N_GRUMPKIN, sig)).toBe(false);
    }
  });
});

describe('merkle tree vs test.nr', () => {
  function zeroLadder(): Fr[] {
    const z: Fr[] = [0n];
    for (let i = 0; i < 8; i++) z.push(p2([z[i], z[i]]));
    return z;
  }
  it('empty depth-8 root', () => {
    expect(zeroLadder()[8]).toBe(EMPTY_ROOT_D8);
  });
  it('leaf(1234,100,0)', () => {
    expect(leafValue(1234n, 100n, 0n)).toBe(LEAF_1234_100_0);
  });
  it('empty account is zero leaf', () => {
    expect(leafValue(0n, 0n, 0n)).toBe(0n);
  });
  it('single leaf at index 5 root + verifyPath', () => {
    const z = zeroLadder();
    const siblings = z.slice(0, 8);
    const leaf = leafValue(1234n, 100n, 0n);
    expect(computeRoot(leaf, 5, siblings)).toBe(ROOT_LEAF_AT_5);
    expect(verifyPath(leaf, 5, siblings, ROOT_LEAF_AT_5)).toBe(true);
    // negatives
    expect(verifyPath(leaf, 6, siblings, ROOT_LEAF_AT_5)).toBe(false);
    expect(verifyPath(leaf, 5, siblings, EMPTY_ROOT_D8)).toBe(false);
    const tampered = [...siblings];
    tampered[0] = 1n;
    expect(verifyPath(leaf, 5, tampered, ROOT_LEAF_AT_5)).toBe(false);
  });
});
